version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elknetwork
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.1
    container_name: logstash
    hostname: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - logstash:/etc/logstash/conf.d/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
        - elknetwork
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    hostname: kibana
    volumes:
      - kibana:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
        - elknetwork
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
    driver: local
  logstash:
    driver: local
  kibana:
    driver: local

networks:
  elknetwork:
    driver: bridge