version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    networks:
        - elknetwork
  logstash:
    image: logstash:7.7.0
    container_name: logstash
    hostname: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/:/etc/logstash/conf.d/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
        - elknetwork
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    volumes:
      - ./kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
        - elknetwork
    depends_on:
      - elasticsearch

volumes:
    elasticsearch: {}
    logstash: {}
    kibana:{}
    
networks:
     elknetwork:
            driver: bridge